
name: Go
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
env:
  APP_DB_USERNAME: postgres
  APP_DB_PASSWORD: password
  APP_DB_NAME: postgres
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
 
      - name: Install dependencies
        run: go mod tidy
 
      - name: Start services
        run: docker compose up -d
 
      - name: Run tests
        run: go test -v ./...
 
      - name: Build project
        run: go build -v ./...
 
  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Run SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v5.0.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=yungAnsem
            -Dsonar.projectKey=CDAS-Grabmair
            -Dsonar.sources=.
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}