name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
env:
  APP_DB_USERNAME: postgres
  APP_DB_PASSWORD: password
  APP_DB_NAME: postgres

jobs:

  build:
    name: Build and Test Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    # Start postgresql docker container
    - name: Start postgresql Container
      run: docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=${APP_DB_PASSWORD} -e POSTGRES_USER=${APP_DB_USERNAME} -e POSTGRES_DB=${APP_DB_NAME} -d postgres

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...