name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_DB_USERNAME: postgres
  APP_DB_PASSWORD: password
  APP_DB_NAME: postgres

jobs:
  build:
    name: Build, Test, Analyze
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Start PostgreSQL container
      run: |
        docker run --name postgres \
          -p 5432:5432 \
          -e POSTGRES_PASSWORD=${APP_DB_PASSWORD} \
          -e POSTGRES_USER=${APP_DB_USERNAME} \
          -e POSTGRES_DB=${APP_DB_NAME} \
          -d postgres

    - name: Wait for PostgreSQL to be ready
      run: |
        until docker exec postgres pg_isready -U ${APP_DB_USERNAME}; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Download Go dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  sonarcloud:
    runs-on: ubuntu-latest 
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Run SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v5.0.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=yungAnsem
            -Dsonar.projectKey='Arthur Grabmair_CDAS-Grabmair'
            -Dsonar.sources=.
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

