name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_DB_USERNAME: postgres
  APP_DB_PASSWORD: password
  APP_DB_NAME: postgres

jobs:
  build:
    name: Build, Test, Analyze
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Start PostgreSQL container
      run: |
        docker run --name postgres \
          -p 5432:5432 \
          -e POSTGRES_PASSWORD=${APP_DB_PASSWORD} \
          -e POSTGRES_USER=${APP_DB_USERNAME} \
          -e POSTGRES_DB=${APP_DB_NAME} \
          -d postgres

    - name: Wait for PostgreSQL to be ready
      run: |
        until docker exec postgres pg_isready -U ${APP_DB_USERNAME}; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Download Go dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@main
      with:
        organization: yungAnsem             
        projectKey: CDAS-Grabmair
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
